name: Build Sirius

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Clone repo
        shell: pwsh
        run: |
          $url = "https://x-access-token:$env:GITHUB_TOKEN@github.com/$env:GITHUB_REPOSITORY.git"
          git clone $url "$env:GITHUB_WORKSPACE"
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install Vulkan SDK
        shell: pwsh
        run: .\.ci\scripts\windows\install-vulkan-sdk.ps1

      - name: Install Qt6
        shell: pwsh
        run: |
          pip install aqtinstall -q 2>&1 | Out-Null
          aqt install-qt windows desktop 6.8.0 win64_msvc2022_64 --outputdir C:\Qt -m qtmultimedia
          Add-Content $env:GITHUB_PATH "C:\Qt\6.8.0\msvc2022_64\bin"

      - name: Configure CMake
        shell: pwsh
        run: |
          $env:Qt6_DIR = "C:\Qt\6.8.0\msvc2022_64\lib\cmake\Qt6"
          glslangValidator --version
          cmake -B build -S . -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DYUZU_USE_BUNDLED_QT=OFF -DENABLE_SDL2=OFF -DENABLE_QT6=ON -DYUZU_USE_BUNDLED_VCPKG=ON -DYUZU_TESTS=OFF

      - name: Build
        shell: pwsh
        run: cmake --build build --config Release -j $env:NUMBER_OF_PROCESSORS --verbose

      - uses: actions/upload-artifact@v4
        with:
          name: Sirius-Windows-x64
          path: build/bin/Release/
