name: Build Sirius

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Clone repo
        shell: pwsh
        run: |
          $url = "https://x-access-token:$env:GITHUB_TOKEN@github.com/$env:GITHUB_REPOSITORY.git"
          git clone --depth 1 $url "$env:GITHUB_WORKSPACE"

      - name: Init submodules
        shell: pwsh
        run: |
          $url = "https://x-access-token:$env:GITHUB_TOKEN@github.com/$env:GITHUB_REPOSITORY.git"
          git remote set-url origin $url
          git submodule sync --recursive
          git submodule update --init --depth 1 2>&1 | Out-String

      - name: Install Qt6
        shell: pwsh
        run: |
          pip install aqtinstall -q 2>&1 | Out-Null
          aqt install-qt windows desktop 6.8.0 win64_msvc2022_64 --outputdir C:\Qt -m qtmultimedia
          Add-Content $env:GITHUB_PATH "C:\Qt\6.8.0\msvc2022_64\bin"
          Add-Content $env:GITHUB_ENV "Qt6_DIR=C:\Qt\6.8.0\msvc2022_64\lib\cmake\Qt6"

      - name: Configure CMake
        run: cmake -B build -S . -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DYUZU_USE_BUNDLED_QT=OFF -DENABLE_SDL2=OFF -DENABLE_QT6=ON -DYUZU_ENABLE_LTO=ON -DYUZU_TESTS=OFF -DYUZU_USE_BUNDLED_VCPKG=ON

      - name: Build
        run: cmake --build build --config Release -j $env:NUMBER_OF_PROCESSORS

      - uses: actions/upload-artifact@v4
        with:
          name: Sirius-Windows-x64
          path: build/bin/Release/
