name: Build Sirius

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        shell: pwsh
        run: |
          $repo = "$env:GITHUB_SERVER_URL/$env:GITHUB_REPOSITORY"
          git -c http.extraheader="AUTHORIZATION: bearer $env:GITHUB_TOKEN" clone --depth 1 $repo src
          Move-Item -Path src\* -Destination . -Force
          Remove-Item -Path src -Recurse -Force -ErrorAction SilentlyContinue

      - name: Init submodules
        shell: pwsh
        run: |
          git -c http.extraheader="AUTHORIZATION: bearer $env:GITHUB_TOKEN" submodule sync --recursive
          git -c http.extraheader="AUTHORIZATION: bearer $env:GITHUB_TOKEN" submodule update --init --depth 1

      - name: Install Qt6
        shell: pwsh
        run: |
          pip install aqtinstall 2>&1 | Out-Null
          aqt install-qt windows desktop 6.6.3 win64_msvc2022_64 --outputdir C:\Qt -m qtmultimedia
          Add-Content $env:GITHUB_PATH "C:\Qt\6.6.3\msvc2022_64\bin"
          Add-Content $env:GITHUB_ENV "Qt6_DIR=C:\Qt\6.6.3\msvc2022_64\lib\cmake\Qt6"

      - name: Configure CMake
        run: cmake -B build -S . -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DYUZU_USE_BUNDLED_QT=OFF -DENABLE_QT6=ON -DYUZU_ENABLE_LTO=ON -DYUZU_TESTS=OFF -DYUZU_USE_BUNDLED_VCPKG=ON

      - name: Build
        run: cmake --build build --config Release -j $env:NUMBER_OF_PROCESSORS

      - uses: actions/upload-artifact@v4
        with:
          name: Sirius-Windows-x64
          path: build/bin/Release/
